#ifndef PARTICLE_NEIGHBORHOOD_ITERATOR_H
#define PARTICLE_NEIGHBORHOOD_ITERATOR_H

#define PARTICLE_NEIGHBORHOOD_ITERATOR_H_BINDING_COUNT 3

PARTICLE_NEIGHBORHOOD_ITERATOR_BINDING_OFFSET
layout(binding = PARTICLE_NEIGHBORHOOD_ITERATOR_BINDING_OFFSET + 0) readonly buffer PNI_PERMUTATION { uint pni_permutation[]; };
layout(binding = PARTICLE_NEIGHBORHOOD_ITERATOR_BINDING_OFFSET + 1) readonly buffer PNI_CELL_KEYS { uint pni_cell_keys[]; };
layout(binding = PARTICLE_NEIGHBORHOOD_ITERATOR_BINDING_OFFSET + 2) readonly buffer PNI_START_ID { uvec2 pni_start_id[]; };

// ToDo Finish
#endif